package httpRespone

// TradeDataResponse 定义 Birdeye API 返回的交易数据
type TradeDataResponse struct {
	Data    TradeData `json:"data"`    // 交易数据
	Success bool      `json:"success"` // 请求是否成功
}

type TradeData struct {
	Address                      string   `json:"address"`
	Holder                       int      `json:"holder"`
	Market                       int      `json:"market"`
	LastTradeUnixTime            int64    `json:"last_trade_unix_time"`
	LastTradeHumanTime           string   `json:"last_trade_human_time"`
	Price                        float64  `json:"price"`
	History30mPrice              float64  `json:"history_30m_price"`
	PriceChange30mPercent        float64  `json:"price_change_30m_percent"`
	History1hPrice               float64  `json:"history_1h_price"`
	PriceChange1hPercent         float64  `json:"price_change_1h_percent"`
	History2hPrice               float64  `json:"history_2h_price"`
	PriceChange2hPercent         float64  `json:"price_change_2h_percent"`
	History4hPrice               float64  `json:"history_4h_price"`
	PriceChange4hPercent         float64  `json:"price_change_4h_percent"`
	History6hPrice               float64  `json:"history_6h_price"`
	PriceChange6hPercent         float64  `json:"price_change_6h_percent"`
	History8hPrice               float64  `json:"history_8h_price"`
	PriceChange8hPercent         float64  `json:"price_change_8h_percent"`
	History12hPrice              float64  `json:"history_12h_price"`
	PriceChange12hPercent        float64  `json:"price_change_12h_percent"`
	History24hPrice              float64  `json:"history_24h_price"`
	PriceChange24hPercent        float64  `json:"price_change_24h_percent"`
	UniqueWallet30m              int      `json:"unique_wallet_30m"`
	UniqueWalletHistory30m       int      `json:"unique_wallet_history_30m"`
	UniqueWallet30mChangePercent *float64 `json:"unique_wallet_30m_change_percent"`
	UniqueWallet1h               int      `json:"unique_wallet_1h"`
	UniqueWalletHistory1h        int      `json:"unique_wallet_history_1h"`
	UniqueWallet1hChangePercent  *float64 `json:"unique_wallet_1h_change_percent"`
	UniqueWallet2h               int      `json:"unique_wallet_2h"`
	UniqueWalletHistory2h        int      `json:"unique_wallet_history_2h"`
	UniqueWallet2hChangePercent  *float64 `json:"unique_wallet_2h_change_percent"`
	UniqueWallet4h               int      `json:"unique_wallet_4h"`
	UniqueWalletHistory4h        int      `json:"unique_wallet_history_4h"`
	UniqueWallet4hChangePercent  *float64 `json:"unique_wallet_4h_change_percent"`
	UniqueWallet8h               int      `json:"unique_wallet_8h"`
	UniqueWalletHistory8h        int      `json:"unique_wallet_history_8h"`
	UniqueWallet8hChangePercent  *float64 `json:"unique_wallet_8h_change_percent"`
	UniqueWallet24h              int      `json:"unique_wallet_24h"`
	UniqueWalletHistory24h       int      `json:"unique_wallet_history_24h"`
	UniqueWallet24hChangePercent *float64 `json:"unique_wallet_24h_change_percent"`
	Trade30m                     float64  `json:"trade_30m"`
	TradeHistory30m              float64  `json:"trade_history_30m"`
	Trade30mChangePercent        float64  `json:"trade_30m_change_percent"`
	Sell30m                      float64  `json:"sell_30m"`
	SellHistory30m               float64  `json:"sell_history_30m"`
	Sell30mChangePercent         float64  `json:"sell_30m_change_percent"`
	Buy30m                       float64  `json:"buy_30m"`
	BuyHistory30m                float64  `json:"buy_history_30m"`
	Buy30mChangePercent          float64  `json:"buy_30m_change_percent"`
	Volume30m                    float64  `json:"volume_30m"`
	Volume30mUsd                 float64  `json:"volume_30m_usd"`
	VolumeHistory30m             float64  `json:"volume_history_30m"`
	VolumeHistory30mUsd          float64  `json:"volume_history_30m_usd"`
	Volume30mChangePercent       float64  `json:"volume_30m_change_percent"`
	VolumeBuy30m                 float64  `json:"volume_buy_30m"`
	VolumeBuy30mUsd              float64  `json:"volume_buy_30m_usd"`
	VolumeBuyHistory30m          float64  `json:"volume_buy_history_30m"`
	VolumeBuyHistory30mUsd       float64  `json:"volume_buy_history_30m_usd"`
	VolumeBuy30mChangePercent    float64  `json:"volume_buy_30m_change_percent"`
	VolumeSell30m                float64  `json:"volume_sell_30m"`
	VolumeSell30mUsd             float64  `json:"volume_sell_30m_usd"`
	VolumeSellHistory30m         float64  `json:"volume_sell_history_30m"`
	VolumeSellHistory30mUsd      float64  `json:"volume_sell_history_30m_usd"`
	VolumeSell30mChangePercent   float64  `json:"volume_sell_30m_change_percent"`
	Trade1h                      float64  `json:"trade_1h"`
	TradeHistory1h               float64  `json:"trade_history_1h"`
	Trade1hChangePercent         float64  `json:"trade_1h_change_percent"`
	Sell1h                       float64  `json:"sell_1h"`
	SellHistory1h                float64  `json:"sell_history_1h"`
	Sell1hChangePercent          float64  `json:"sell_1h_change_percent"`
	Buy1h                        float64  `json:"buy_1h"`
	BuyHistory1h                 float64  `json:"buy_history_1h"`
	Buy1hChangePercent           float64  `json:"buy_1h_change_percent"`
	Volume1h                     float64  `json:"volume_1h"`
	Volume1hUSD                  float64  `json:"volume_1h_usd"`
	VolumeHistory1h              float64  `json:"volume_history_1h"`
	VolumeHistory1hUSD           float64  `json:"volume_history_1h_usd"`
	Volume1hChangePercent        float64  `json:"volume_1h_change_percent"`
	VolumeBuy1h                  float64  `json:"volume_buy_1h"`
	VolumeBuy1hUSD               float64  `json:"volume_buy_1h_usd"`
	VolumeBuyHistory1h           float64  `json:"volume_buy_history_1h"`
	VolumeBuyHistory1hUSD        float64  `json:"volume_buy_history_1h_usd"`
	VolumeBuy1hChangePercent     float64  `json:"volume_buy_1h_change_percent"`
	VolumeSell1h                 float64  `json:"volume_sell_1h"`
	VolumeSell1hUSD              float64  `json:"volume_sell_1h_usd"`
	VolumeSellHistory1h          float64  `json:"volume_sell_history_1h"`
	VolumeSellHistory1hUSD       float64  `json:"volume_sell_history_1h_usd"`
	VolumeSell1hChangePercent    float64  `json:"volume_sell_1h_change_percent"`
	Trade2h                      float64  `json:"trade_2h"`
	TradeHistory2h               float64  `json:"trade_history_2h"`
	Trade2hChangePercent         float64  `json:"trade_2h_change_percent"`
	Sell2h                       float64  `json:"sell_2h"`
	SellHistory2h                float64  `json:"sell_history_2h"`
	Sell2hChangePercent          float64  `json:"sell_2h_change_percent"`
	Buy2h                        float64  `json:"buy_2h"`
	BuyHistory2h                 float64  `json:"buy_history_2h"`
	Buy2hChangePercent           float64  `json:"buy_2h_change_percent"`
	Volume2h                     float64  `json:"volume_2h"`
	Volume2hUSD                  float64  `json:"volume_2h_usd"`
	VolumeHistory2h              float64  `json:"volume_history_2h"`
	VolumeHistory2hUSD           float64  `json:"volume_history_2h_usd"`
	Volume2hChangePercent        float64  `json:"volume_2h_change_percent"`
	VolumeBuy2h                  float64  `json:"volume_buy_2h"`
	VolumeBuy2hUSD               float64  `json:"volume_buy_2h_usd"`
	VolumeBuyHistory2h           float64  `json:"volume_buy_history_2h"`
	VolumeBuyHistory2hUSD        float64  `json:"volume_buy_history_2h_usd"`
	VolumeBuy2hChangePercent     float64  `json:"volume_buy_2h_change_percent"`
	VolumeSell2h                 float64  `json:"volume_sell_2h"`
	VolumeSell2hUSD              float64  `json:"volume_sell_2h_usd"`
	VolumeSellHistory2h          float64  `json:"volume_sell_history_2h"`
	VolumeSellHistory2hUSD       float64  `json:"volume_sell_history_2h_usd"`
	VolumeSell2hChangePercent    float64  `json:"volume_sell_2h_change_percent"`
	Trade4h                      float64  `json:"trade_4h"`
	TradeHistory4h               float64  `json:"trade_history_4h"`
	Trade4hChangePercent         float64  `json:"trade_4h_change_percent"`
	Sell4h                       float64  `json:"sell_4h"`
	SellHistory4h                float64  `json:"sell_history_4h"`
	Sell4hChangePercent          float64  `json:"sell_4h_change_percent"`
	Buy4h                        float64  `json:"buy_4h"`
	BuyHistory4h                 float64  `json:"buy_history_4h"`
	Buy4hChangePercent           float64  `json:"buy_4h_change_percent"`
	Volume4h                     float64  `json:"volume_4h"`
	Volume4hUSD                  float64  `json:"volume_4h_usd"`
	VolumeHistory4h              float64  `json:"volume_history_4h"`
	VolumeHistory4hUSD           float64  `json:"volume_history_4h_usd"`
	Volume4hChangePercent        float64  `json:"volume_4h_change_percent"`
	VolumeBuy4h                  float64  `json:"volume_buy_4h"`
	VolumeBuy4hUSD               float64  `json:"volume_buy_4h_usd"`
	VolumeBuyHistory4h           float64  `json:"volume_buy_history_4h"`
	VolumeBuyHistory4hUSD        float64  `json:"volume_buy_history_4h_usd"`
	VolumeBuy4hChangePercent     float64  `json:"volume_buy_4h_change_percent"`
	VolumeSell4h                 float64  `json:"volume_sell_4h"`
	VolumeSell4hUSD              float64  `json:"volume_sell_4h_usd"`
	VolumeSellHistory4h          float64  `json:"volume_sell_history_4h"`
	VolumeSellHistory4hUSD       float64  `json:"volume_sell_history_4h_usd"`
	VolumeSell4hChangePercent    float64  `json:"volume_sell_4h_change_percent"`
	Trade8h                      float64  `json:"trade_8h"`
	TradeHistory8h               float64  `json:"trade_history_8h"`
	Trade8hChangePercent         float64  `json:"trade_8h_change_percent"`
	Sell8h                       float64  `json:"sell_8h"`
	SellHistory8h                float64  `json:"sell_history_8h"`
	Sell8hChangePercent          float64  `json:"sell_8h_change_percent"`
	Buy8h                        float64  `json:"buy_8h"`
	BuyHistory8h                 float64  `json:"buy_history_8h"`
	Buy8hChangePercent           float64  `json:"buy_8h_change_percent"`
	Volume8h                     float64  `json:"volume_8h"`
	Volume8hUSD                  float64  `json:"volume_8h_usd"`
	VolumeHistory8h              float64  `json:"volume_history_8h"`
	VolumeHistory8hUSD           float64  `json:"volume_history_8h_usd"`
	Volume8hChangePercent        float64  `json:"volume_8h_change_percent"`
	VolumeBuy8h                  float64  `json:"volume_buy_8h"`
	VolumeBuy8hUSD               float64  `json:"volume_buy_8h_usd"`
	VolumeBuyHistory8h           float64  `json:"volume_buy_history_8h"`
	VolumeBuyHistory8hUSD        float64  `json:"volume_buy_history_8h_usd"`
	VolumeBuy8hChangePercent     float64  `json:"volume_buy_8h_change_percent"`
	VolumeSell8h                 float64  `json:"volume_sell_8h"`
	VolumeSell8hUSD              float64  `json:"volume_sell_8h_usd"`
	VolumeSellHistory8h          float64  `json:"volume_sell_history_8h"`
	VolumeSellHistory8hUSD       float64  `json:"volume_sell_history_8h_usd"`
	VolumeSell8hChangePercent    float64  `json:"volume_sell_8h_change_percent"`
	Trade24h                     float64  `json:"trade_24h"`
	TradeHistory24h              float64  `json:"trade_history_24h"`
	Trade24hChangePercent        float64  `json:"trade_24h_change_percent"`
	Sell24h                      float64  `json:"sell_24h"`
	SellHistory24h               float64  `json:"sell_history_24h"`
	Sell24hChangePercent         float64  `json:"sell_24h_change_percent"`
	Buy24h                       float64  `json:"buy_24h"`
	BuyHistory24h                float64  `json:"buy_history_24h"`
	Buy24hChangePercent          float64  `json:"buy_24h_change_percent"`
	Volume24h                    float64  `json:"volume_24h"`
	Volume24hUSD                 float64  `json:"volume_24h_usd"`
	VolumeHistory24h             float64  `json:"volume_history_24h"`
	VolumeHistory24hUSD          float64  `json:"volume_history_24h_usd"`
	Volume24hChangePercent       float64  `json:"volume_24h_change_percent"`
	VolumeBuy24h                 float64  `json:"volume_buy_24h"`
	VolumeBuy24hUSD              float64  `json:"volume_buy_24h_usd"`
	VolumeBuyHistory24h          float64  `json:"volume_buy_history_24h"`
	VolumeBuyHistory24hUSD       float64  `json:"volume_buy_history_24h_usd"`
	VolumeBuy24hChangePercent    float64  `json:"volume_buy_24h_change_percent"`
	VolumeSell24h                float64  `json:"volume_sell_24h"`
	VolumeSell24hUSD             float64  `json:"volume_sell_24h_usd"`
	VolumeSellHistory24h         float64  `json:"volume_sell_history_24h"`
	VolumeSellHistory24hUSD      float64  `json:"volume_sell_history_24h_usd"`
	VolumeSell24hChangePercent   float64  `json:"volume_sell_24h_change_percent"`
}
