// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ws/kline/{tokenAddress}": {
            "get": {
                "description": "通过 WebSocket 实时推送 K 线数据。连接成功后，服务器将每秒推送最新的K线数据。\n连接格式: ws://host/api/v1/ws/kline/{tokenAddress}?resolution={resolution}\n示例(Solana): ws://localhost:4881/api/v1/ws/kline/8iFREvVdmLKxVeibpC5VLRr1S6X5dm7gYR3VCU1wpump?resolution=1S\n连接成功后，可以发送 \"subscribe\" 消息来开始接收数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kline-data"
                ],
                "summary": "K线数据 WebSocket 接口",
                "parameters": [
                    {
                        "type": "string",
                        "example": "8iFREvVdmLKxVeibpC5VLRr1S6X5dm7gYR3VCU1wpump",
                        "description": "代币地址",
                        "name": "tokenAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "1S",
                            "1",
                            "5",
                            "15",
                            "60",
                            "240",
                            "720",
                            "1D"
                        ],
                        "type": "string",
                        "example": "1S",
                        "description": "K线周期",
                        "name": "resolution",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket连接成功后的推送数据格式",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.KlineData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "close": {
                                            "type": "string"
                                        },
                                        "high": {
                                            "type": "string"
                                        },
                                        "low": {
                                            "type": "string"
                                        },
                                        "open": {
                                            "type": "string"
                                        },
                                        "timestamp": {
                                            "type": "integer"
                                        },
                                        "volume": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/global/{chain_type}/native_balance": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户地址获取用户的钱包原生代币余额。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局数据"
                ],
                "summary": "获取链的原生代币钱包余额",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回原生代币余额",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenBalance"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/global/{chain_type}/native_token_price": {
            "get": {
                "description": "根据链类型获取原生代币的 USD 价格，保留 8 位小数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局数据"
                ],
                "summary": "获取链的原生代币价格",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回原生代币价格",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/global/{chain_type}/ticker_balance/{ticker_address}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户地址获取用户的钱包原生代币余额。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局数据"
                ],
                "summary": "获取链的原生代币钱包余额",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "ticker_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回原生代币余额",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenBalance"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/klines/{klineType}/{chainType}/{tokenAddress}": {
            "get": {
                "description": "Get historical kline (candlestick) data for a specific token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kline-data"
                ],
                "summary": "Get token kline data",
                "parameters": [
                    {
                        "enum": [
                            "kline",
                            "mcapkline"
                        ],
                        "type": "string",
                        "description": "Kline type (kline for price data, mcapkline for market cap data)",
                        "name": "klineType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "sol",
                            "eth",
                            "bsc"
                        ],
                        "type": "string",
                        "description": "Chain type",
                        "name": "chainType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token address",
                        "name": "tokenAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "1S",
                            "1",
                            "5",
                            "15",
                            "60",
                            "240",
                            "720",
                            "1D"
                        ],
                        "type": "string",
                        "description": "Resolution of kline data",
                        "name": "resolution",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Start timestamp in seconds",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "End timestamp in seconds",
                        "name": "till",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.KlineData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/points/{chain_type}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户 ID 获取用户的交易积分、邀请积分和可用积分。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分"
                ],
                "summary": "获取用户积分数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户积分数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.PointsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/points/{chain_type}/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户 ID 获取用户的积分明细数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分"
                ],
                "summary": "获取用户积分明细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "游标",
                        "name": "cursor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户积分明细",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.PointsDetailsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/points/{chain_type}/estimated": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户 ID 获取用户的预估积分数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "积分"
                ],
                "summary": "获取用户预估积分数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户预估积分数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.PointsEstimatedResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/points/{chain_type}/invite/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户 ID 获取用户的积分统计数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户邀请明细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "游标",
                        "name": "cursor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户积分明细",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.InvitedPointsTotalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/swap/{chain_type}/get_transaction": {
            "get": {
                "description": "根据链类型、交易类型和请求参数获取 Swap 路由。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Swap"
                ],
                "summary": "获取 Swap 路由",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易类型（buy 或 sell）",
                        "name": "tradeType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "发送地址（用户地址）",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "输入代币地址",
                        "name": "token_in_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "输出代币地址",
                        "name": "token_out_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "输入代币所在链（sol、eth、bsc）",
                        "name": "token_in_chain",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "输出代币所在链（sol、eth、bsc）",
                        "name": "token_out_chain",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "输入金额（单位：最小代币单位，如 lamports、wei）",
                        "name": "in_amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "交易优先费（单位：最小代币单位，如 lamports）",
                        "name": "priority_fee",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "滑点（100 * 100 代表 1%）",
                        "name": "slippage",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否启用 Anti-MEV（默认 false）",
                        "name": "is_anti_mev",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否使用 Legacy 交易模式（默认 false）",
                        "name": "legacy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "交易方向（buy 或 sell，可选）",
                        "name": "swap_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "积分数（用于 g_points 交易类型）",
                        "name": "points",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "交易平台类型（pump、raydium、game、g_external、g_points）",
                        "name": "platform_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 Swap 路由信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/swap/{chain_type}/send_transaction": {
            "post": {
                "description": "根据链类型和 Swap 交易数据发送 Swap 请求。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Swap"
                ],
                "summary": "发送 Swap 请求",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Swap 交易数据（Base64 编码）",
                        "name": "swap_transaction",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否启用 Anti-MEV（默认为 false）",
                        "name": "is_anti_mev",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回交易结果",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/swap/{chain_type}/transaction_status": {
            "get": {
                "description": "根据链类型和交易签名获取 Swap 请求状态。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Swap"
                ],
                "summary": "获取 Swap 请求状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易签名",
                        "name": "swap_transaction",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回交易状态",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}": {
            "get": {
                "description": "根据链类型、排序、分页和搜索条件获取市场行情数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取市场行情数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "MARKET_CAP",
                            "PRICE_CHANGE_5M",
                            "PRICE_CHANGE_1H",
                            "PRICE_CHANGE_24H",
                            "NATIVE_VOLUME_1H",
                            "NATIVE_VOLUME_24H",
                            "TX_COUNT_24H",
                            "HOLDERS",
                            "INITIALIZE_AT",
                            "Links"
                        ],
                        "type": "string",
                        "example": "\"INITIALIZE_AT\"",
                        "description": "排序字段，支持以下值：MARKET_CAP, PRICE_CHANGE_5M, PRICE_CHANGE_1H, PRICE_CHANGE_24H, NATIVE_VOLUME_1H, NATIVE_VOLUME_24H, TX_COUNT_24H, HOLDERS, INITIALIZE_AT, Links",
                        "name": "sorted_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "DESC",
                            "ASC"
                        ],
                        "type": "string",
                        "example": "\"DESC\"",
                        "description": "排序方向，支持以下值：DESC, ASC",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"\"",
                        "description": "分页游标，用于分页查询",
                        "name": "page_cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 50,
                        "description": "每页返回的数据条数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"\"",
                        "description": "搜索关键字，用于筛选数据",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "1D",
                            "1H",
                            "1M"
                        ],
                        "type": "string",
                        "example": "\"1D\"",
                        "description": "新交易对的时间分辨率，例如 1D（1 天）",
                        "name": "new_pairs_resolution",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回市场行情数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TickersResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}/detail/{ticker_address}": {
            "get": {
                "description": "根据链类型和代币地址获取 Ticker 的详细信息。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取 Ticker 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "ticker_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 Ticker 详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetTickerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}/market/{ticker_address}": {
            "get": {
                "description": "根据链类型和代币地址获取 Ticker 的详细信息。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取 Ticker 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "ticker_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 Ticker 详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetTickerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}/search": {
            "get": {
                "description": "根据链类型、搜索参数、分页参数等条件搜索 Tickers。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "搜索 Tickers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索参数（如代币名称或地址）",
                        "name": "param",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分页游标",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 Tickers 列表",
                        "schema": {
                            "$ref": "#/definitions/response.SearchTickerResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}/swap_histories/{ticker_address}": {
            "get": {
                "description": "根据链类型和代币地址获取交易历史记录。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取指定 Ticker 的交易历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "ticker_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回交易历史记录",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SwapHistoriesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{chain_type}/token_distribution/{ticker_address}": {
            "get": {
                "description": "根据链类型和代币地址获取代币持有者的分布信息。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取指定 Ticker 的代币分布信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "ticker_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币分布信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenDistributionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/token_holdings/{chain_type}/histories/{account}": {
            "get": {
                "description": "根据链类型和用户账户获取代币持仓历史数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "代币持仓"
                ],
                "summary": "获取代币持仓历史数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0",
                        "description": "分页页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "20",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币持仓历史数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenHoldingHistoriesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/token_holdings/{chain_type}/{account}": {
            "get": {
                "description": "根据链类型、用户账户和目标账户获取代币持仓数据。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "代币持仓"
                ],
                "summary": "获取代币持仓数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标账户",
                        "name": "account",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "false",
                        "description": "是否包含零余额",
                        "name": "allow_zero_balance",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币持仓数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenHoldingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users/{chain_type}/invite/code": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和用户 ID 获取用户的邀请码和邀请数量。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户邀请码信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户邀请码信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.InviteCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users/{chain_type}/login": {
            "post": {
                "description": "通过钱包地址和签名进行登录。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户钱包登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "登录请求参数",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users/{chain_type}/my_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据链类型和 JWT Token 获取当前用户的详细信息。支持的链类型：sol（Solana）、eth（Ethereum）、bsc（Binance Smart Chain）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链类型（sol、eth、bsc）",
                        "name": "chain_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MyInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "description": "用户登录时提交的请求参数",
            "type": "object",
            "properties": {
                "address": {
                    "description": "用户钱包地址",
                    "type": "string",
                    "example": "F59CSoJEmjDFQWZMjSjjvu6q7xV31p9rPzRynwrE71yk"
                },
                "comment_id": {
                    "description": "评论ID（可选）",
                    "type": "string",
                    "example": ""
                },
                "invite_code": {
                    "description": "邀请码（可选）",
                    "type": "string",
                    "example": "INVITE123"
                },
                "message": {
                    "description": "登录消息",
                    "type": "string",
                    "example": "Sign in to the super.exchange\r\n\r\nTimestamp: 1740885327"
                },
                "post_id": {
                    "description": "帖子ID（可选）",
                    "type": "string",
                    "example": ""
                },
                "signature": {
                    "description": "签名信息",
                    "type": "string",
                    "example": "Pli28P7PHx6Mzh+RwRTcqtCSuNs2qlncAqC4tK9PFN/CLnvZ2Gm8koqvkLPEZNoiVJOX71hCBaQV9NUKVX8KDg=="
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string",
                    "example": "1740885327"
                }
            }
        },
        "response.GetTickerResponse": {
            "description": "Ticker 的具体数据",
            "type": "object",
            "properties": {
                "market": {
                    "description": "市场信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Market"
                        }
                    ]
                },
                "market_metadata": {
                    "description": "市场元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketMetadata"
                        }
                    ]
                },
                "market_ticker": {
                    "description": "市场行情",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketTicker"
                        }
                    ]
                }
            }
        },
        "response.InviteCodeResponse": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "description": "邀请码",
                    "type": "string",
                    "example": "GT4L5B"
                },
                "invite_count": {
                    "description": "邀请数量",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "response.InvitedPointsDetail": {
            "type": "object",
            "properties": {
                "invite_time": {
                    "type": "integer"
                },
                "invitee": {
                    "type": "string"
                },
                "trading_points": {
                    "type": "string"
                }
            }
        },
        "response.InvitedPointsTotalResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "integer"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.InvitedPointsDetail"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "response.KlineData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "response.LoginResponse": {
            "description": "登录成功后返回的具体数据",
            "type": "object",
            "properties": {
                "expire_time": {
                    "description": "邀请码",
                    "type": "string",
                    "example": ""
                },
                "token": {
                    "description": "登录令牌",
                    "type": "string",
                    "example": "_vetZFMHLOlPWer8_uTrqe5_7gGGNPi-fvD--pomTdSd2kn3po2uBujC4o7raUiNHPpKJaS_BR3jmgOEdaAEFA=="
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserInfo"
                        }
                    ]
                }
            }
        },
        "response.Market": {
            "description": "市场的基本信息",
            "type": "object",
            "properties": {
                "create_timestamp": {
                    "type": "integer",
                    "example": 1740033455
                },
                "creator": {
                    "description": "创建者地址",
                    "type": "string",
                    "example": "3P3PMv28AM7SvNkGmAdHCusPwahSB9QG9z5o4gTvmNBX"
                },
                "decimals": {
                    "description": "代币铸造地址",
                    "type": "integer",
                    "example": 6
                },
                "holders": {
                    "type": "integer",
                    "example": 4204
                },
                "market": {
                    "description": "市场地址",
                    "type": "string",
                    "example": "B3o198GX45DZ9HeJZ56wuruyWWCfGVBSn5qC71q5AHZz"
                },
                "market_id": {
                    "description": "市场ID",
                    "type": "integer",
                    "example": 1
                },
                "native_vault": {
                    "description": "原生代币金库地址",
                    "type": "string",
                    "example": "98J2RACW3wk8u36k1cPmDenzHdPjhcd5qXsm5g471kdh"
                },
                "price": {
                    "description": "当前价格",
                    "type": "number",
                    "example": 0.000050417320729
                },
                "rank": {
                    "type": "integer",
                    "example": 1
                },
                "token_mint": {
                    "description": "代币铸造地址",
                    "type": "string",
                    "example": "suprkbfvwpFZXzWaoKjTzGkW1nkvvwK9n2E6g1zyLFo"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string",
                    "example": "§uper Exchange"
                },
                "token_symbol": {
                    "description": "代币符号",
                    "type": "string",
                    "example": "SUPER"
                },
                "token_vault": {
                    "description": "代币金库地址",
                    "type": "string",
                    "example": "9SQy9T4pzadupDcWdYYgFmUgXLVydfQwgKZEbzeACNAQ"
                },
                "uri": {
                    "description": "URI",
                    "type": "string",
                    "example": "https://static.super.exchange/m/official/super.json"
                }
            }
        },
        "response.MarketMetadata": {
            "description": "市场的元数据信息",
            "type": "object",
            "properties": {
                "banner": {
                    "description": "横幅图片",
                    "type": "string",
                    "example": ""
                },
                "description": {
                    "description": "描述",
                    "type": "string",
                    "example": ""
                },
                "github": {
                    "type": "string"
                },
                "image_url": {
                    "description": "图片URL",
                    "type": "string",
                    "example": "https://static.super.exchange/i/official/super.png"
                },
                "rules": {
                    "description": "规则",
                    "type": "string",
                    "example": ""
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "example": 0
                },
                "telegram": {
                    "description": "Telegram链接",
                    "type": "string",
                    "example": "https://t.me/SuperExchangeCommunity"
                },
                "twitter": {
                    "description": "Twitter链接",
                    "type": "string",
                    "example": "https://x.com/_superexchange"
                },
                "website": {
                    "description": "网站链接",
                    "type": "string",
                    "example": "https://super.exchange"
                }
            }
        },
        "response.MarketResponse": {
            "type": "object",
            "properties": {
                "market": {
                    "description": "市场数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Market"
                        }
                    ]
                },
                "market_metadata": {
                    "description": "市场元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketMetadata"
                        }
                    ]
                },
                "market_ticker": {
                    "description": "市场 Ticker 数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketTicker"
                        }
                    ]
                }
            }
        },
        "response.MarketTicker": {
            "description": "市场的行情数据",
            "type": "object",
            "properties": {
                "Sell_tx_count_24h": {
                    "type": "integer",
                    "example": 7566
                },
                "buy_token_volume_1h": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "buy_token_volume_1h_usd": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "buy_token_volume_24h": {
                    "type": "string",
                    "example": "15435782.918031"
                },
                "buy_token_volume_24h_usd": {
                    "type": "string",
                    "example": "15435782.918031"
                },
                "buy_token_volume_30m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "buy_token_volume_30m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "buy_token_volume_5m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "buy_token_volume_5m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "buy_tx_count_1h": {
                    "type": "integer",
                    "example": 271
                },
                "buy_tx_count_24h": {
                    "type": "integer",
                    "example": 7566
                },
                "buy_tx_count_30m": {
                    "type": "integer",
                    "example": 25
                },
                "buy_tx_count_5m": {
                    "type": "integer",
                    "example": 25
                },
                "last_swap_at": {
                    "type": "integer",
                    "example": 1740887399
                },
                "market_cap": {
                    "type": "string",
                    "example": "50417.320729000000000"
                },
                "price_change_1h": {
                    "type": "string",
                    "example": "0.005103"
                },
                "price_change_24h": {
                    "type": "string",
                    "example": "0.224965"
                },
                "price_change_30m": {
                    "type": "string",
                    "example": "0.000836"
                },
                "price_change_5m": {
                    "type": "string",
                    "example": "0.000836"
                },
                "sell_token_volume_1h": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "sell_token_volume_1h_usd": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "sell_token_volume_24h": {
                    "type": "string",
                    "example": "15435782.918031"
                },
                "sell_token_volume_24h_usd": {
                    "type": "string",
                    "example": "15435782.918031"
                },
                "sell_token_volume_30m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "sell_token_volume_30m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "sell_token_volume_5m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "sell_token_volume_5m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "sell_tx_count_1h": {
                    "type": "integer",
                    "example": 271
                },
                "sell_tx_count_30m": {
                    "type": "integer",
                    "example": 25
                },
                "sell_tx_count_5m": {
                    "type": "integer",
                    "example": 25
                },
                "token_volume_1h": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "token_volume_1h_usd": {
                    "type": "string",
                    "example": "379231.972430"
                },
                "token_volume_24h": {
                    "type": "string",
                    "example": "15450301.872331"
                },
                "token_volume_24h_usd": {
                    "type": "string",
                    "example": "15450301.872331"
                },
                "token_volume_30m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "token_volume_30m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "token_volume_5m": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "token_volume_5m_usd": {
                    "type": "string",
                    "example": "62269.324250"
                },
                "tx_count_1h": {
                    "type": "integer",
                    "example": 271
                },
                "tx_count_24h": {
                    "type": "integer",
                    "example": 7590
                },
                "tx_count_30m": {
                    "type": "integer",
                    "example": 25
                },
                "tx_count_5m": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "response.Moderator": {
            "description": "持有者的管理员信息",
            "type": "object",
            "properties": {
                "banned": {
                    "description": "是否被封禁",
                    "type": "boolean",
                    "example": false
                },
                "banned_mod_id": {
                    "description": "被封禁的 Moderator ID",
                    "type": "integer",
                    "example": 0
                },
                "status": {
                    "description": "当前状态",
                    "type": "string",
                    "example": "NORMAL"
                }
            }
        },
        "response.MyInfoResponse": {
            "description": "包含用户基本信息、社交统计、邀请码等详细信息。",
            "type": "object",
            "properties": {
                "fan_count": {
                    "description": "关注数量",
                    "type": "integer"
                },
                "follow_status": {
                    "description": "关注状态",
                    "type": "string"
                },
                "follower_count": {
                    "description": "粉丝数量",
                    "type": "integer"
                },
                "has_bound": {
                    "description": "是否已绑定",
                    "type": "boolean"
                },
                "invite_code": {
                    "description": "邀请码",
                    "type": "string"
                },
                "inviter_id": {
                    "type": "integer"
                },
                "mention_count": {
                    "description": "提及数量",
                    "type": "integer"
                },
                "parent_inviter_id": {
                    "type": "integer"
                },
                "user": {
                    "description": "用户基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserInfo"
                        }
                    ]
                },
                "vote_count": {
                    "description": "投票数量",
                    "type": "integer"
                }
            }
        },
        "response.PointsDetail": {
            "type": "object",
            "properties": {
                "points": {
                    "description": "积分",
                    "type": "string",
                    "example": "0.000182"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer",
                    "example": 1740840671
                },
                "type": {
                    "description": "类型",
                    "type": "string",
                    "example": "trading"
                }
            }
        },
        "response.PointsDetailsResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "游标",
                    "type": "integer"
                },
                "details": {
                    "description": "积分明细列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PointsDetail"
                    }
                },
                "has_more": {
                    "description": "是否还有更多",
                    "type": "boolean"
                }
            }
        },
        "response.PointsEstimatedResponse": {
            "type": "object",
            "properties": {
                "estimated_points": {
                    "description": "预估积分",
                    "type": "string",
                    "example": "12862.90277"
                }
            }
        },
        "response.PointsResponse": {
            "type": "object",
            "properties": {
                "available_points": {
                    "description": "可用积分",
                    "type": "string",
                    "example": "0.147938"
                },
                "invite_points": {
                    "description": "邀请积分",
                    "type": "string",
                    "example": "0"
                },
                "trading_points": {
                    "description": "交易积分",
                    "type": "string",
                    "example": "0.147938"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SearchTickerResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "游标",
                    "type": "string"
                },
                "has_more": {
                    "description": "是否有更多数据",
                    "type": "boolean"
                },
                "posts": {
                    "description": "帖子列表",
                    "type": "array",
                    "items": {}
                },
                "tickers": {
                    "description": "市场列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MarketResponse"
                    }
                },
                "users": {
                    "description": "用户列表",
                    "type": "array",
                    "items": {}
                }
            }
        },
        "response.SwapHistoriesResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "description": "是否还有更多数据",
                    "type": "boolean"
                },
                "transaction_histories": {
                    "description": "交易历史记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TransactionHistory"
                    }
                }
            }
        },
        "response.TickerItem": {
            "type": "object",
            "properties": {
                "market": {
                    "description": "市场信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Market"
                        }
                    ]
                },
                "market_metadata": {
                    "description": "市场元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketMetadata"
                        }
                    ]
                },
                "market_ticker": {
                    "description": "市场行情",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketTicker"
                        }
                    ]
                }
            }
        },
        "response.TickersResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "分页游标",
                    "type": "string",
                    "example": "NTA0MTcuMzIwNzI5MDAwMDAwMDAwOjE="
                },
                "has_more": {
                    "description": "是否有更多数据",
                    "type": "boolean",
                    "example": true
                },
                "list": {
                    "description": "市场列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TickerItem"
                    }
                }
            }
        },
        "response.TokenBalance": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "decimals": {
                    "type": "integer"
                },
                "owner": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "response.TokenDistributionResponse": {
            "description": "代币持有者数据",
            "type": "object",
            "properties": {
                "token_holders": {
                    "description": "代币持有者列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHolder"
                    }
                }
            }
        },
        "response.TokenHolder": {
            "description": "代币持有者详情",
            "type": "object",
            "properties": {
                "account": {
                    "description": "持有者钱包地址",
                    "type": "string",
                    "example": "669VYcBRq51iQzFiPTQcsW2CsvLfHM9AwVmaoM1mAAR7"
                },
                "amount": {
                    "description": "持有代币的数量",
                    "type": "string"
                },
                "is_associated_bonding_curve": {
                    "description": "是否与 Bonding Curve 关联",
                    "type": "boolean",
                    "example": false
                },
                "is_black_hole": {
                    "description": "是否为黑洞地址",
                    "type": "boolean",
                    "example": false
                },
                "is_community_vault": {
                    "description": "是否为社区金库",
                    "type": "boolean",
                    "example": false
                },
                "moderator": {
                    "description": "持有者的管理员信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Moderator"
                        }
                    ]
                },
                "percentage": {
                    "description": "持有代币的百分比",
                    "type": "string",
                    "example": "100.000000"
                },
                "ui_amount": {
                    "description": "代币的 UI 显示数量",
                    "type": "number"
                },
                "user_profile": {
                    "description": "用户资料（可能为空）"
                }
            }
        },
        "response.TokenHolding": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "持仓数量",
                    "type": "string"
                },
                "filled_price": {
                    "description": "成交价格",
                    "type": "string"
                },
                "holders_count": {
                    "description": "持有者数量",
                    "type": "integer"
                },
                "id": {
                    "description": "代币 ID",
                    "type": "integer"
                },
                "image_uri": {
                    "description": "代币图片 URI",
                    "type": "string"
                },
                "market_address": {
                    "description": "市场地址",
                    "type": "string"
                },
                "market_id": {
                    "description": "市场 ID",
                    "type": "integer"
                },
                "price": {
                    "description": "当前价格",
                    "type": "string"
                },
                "realized_pnl": {
                    "description": "已实现盈亏",
                    "type": "string"
                },
                "symbol": {
                    "description": "代币符号",
                    "type": "string"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string"
                },
                "total_buy": {
                    "description": "总买入数量",
                    "type": "string"
                },
                "total_buy_native": {
                    "description": "总买入原生代币数量",
                    "type": "string"
                },
                "total_sell": {
                    "description": "总卖出数量",
                    "type": "string"
                },
                "total_sell_native": {
                    "description": "总卖出原生代币数量",
                    "type": "string"
                },
                "total_value": {
                    "description": "持仓总价值",
                    "type": "string"
                }
            }
        },
        "response.TokenHoldingHistoriesResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "description": "是否有更多数据",
                    "type": "boolean"
                },
                "token_holdings_histories": {
                    "description": "代币持仓历史列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHoldingHistory"
                    }
                }
            }
        },
        "response.TokenHoldingHistory": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "持仓数量",
                    "type": "string"
                },
                "filled_price": {
                    "description": "成交价格",
                    "type": "string"
                },
                "holders_count": {
                    "description": "持有者数量",
                    "type": "integer"
                },
                "id": {
                    "description": "记录 ID",
                    "type": "integer"
                },
                "image_uri": {
                    "description": "代币图片 URI",
                    "type": "string"
                },
                "market_address": {
                    "description": "市场地址",
                    "type": "string"
                },
                "market_id": {
                    "description": "市场 ID",
                    "type": "integer"
                },
                "price": {
                    "description": "当前价格",
                    "type": "string"
                },
                "realized_pnl": {
                    "description": "已实现盈亏",
                    "type": "string"
                },
                "symbol": {
                    "description": "代币符号",
                    "type": "string"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string"
                },
                "total_buy": {
                    "description": "总买入数量",
                    "type": "string"
                },
                "total_buy_native": {
                    "description": "总买入原生代币数量",
                    "type": "string"
                },
                "total_sell": {
                    "description": "总卖出数量",
                    "type": "string"
                },
                "total_sell_native": {
                    "description": "总卖出原生代币数量",
                    "type": "string"
                },
                "total_value": {
                    "description": "持仓总价值",
                    "type": "string"
                }
            }
        },
        "response.TokenHoldingsResponse": {
            "type": "object",
            "properties": {
                "token_holdings": {
                    "description": "代币持仓列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHolding"
                    }
                }
            }
        },
        "response.TransactionHistory": {
            "type": "object",
            "properties": {
                "block_time": {
                    "description": "区块时间",
                    "type": "integer"
                },
                "native_amount": {
                    "description": "原生代币数量",
                    "type": "string"
                },
                "payer": {
                    "description": "支付方地址",
                    "type": "string"
                },
                "signature": {
                    "description": "交易签名",
                    "type": "string"
                },
                "token_amount": {
                    "description": "Index        int    ` + "`" + `json:\"index\"` + "`" + `         // 交易索引",
                    "type": "string"
                },
                "token_price": {
                    "description": "代币价格",
                    "type": "string"
                },
                "trade_type": {
                    "description": "交易类型：1=买，2=卖，3=回购",
                    "type": "integer"
                }
            }
        },
        "response.UserInfo": {
            "description": "包含用户 ID、地址、昵称、头像和描述等信息。",
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "invite_code": {
                    "type": "string",
                    "example": ""
                },
                "twitter_id": {
                    "type": "string"
                },
                "twitter_username": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "v4-api.frogswap.org",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Game API",
	Description:      "This is a sample API for demonstration purposes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
