// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/global/sol_balance": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据 JWT Token 获取当前用户的 SOL 余额",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局数据"
                ],
                "summary": "获取当前用户的 SOL 余额",
                "responses": {
                    "200": {
                        "description": "成功返回 SOL 余额",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenBalance"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/global/sol_usd_price": {
            "get": {
                "description": "返回 SOL 对 USD 的当前价格，保留 8 位小数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局数据"
                ],
                "summary": "获取 SOL 对 USD 的当前价格",
                "responses": {
                    "200": {
                        "description": "成功返回 SOL 价格",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service is healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tickers": {
            "get": {
                "description": "根据排序、分页和搜索条件获取市场行情数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取市场行情数据",
                "parameters": [
                    {
                        "enum": [
                            "MARKET_CAP",
                            "PRICE_CHANGE_5M",
                            "PRICE_CHANGE_1H",
                            "PRICE_CHANGE_24H",
                            "NATIVE_VOLUME_1H",
                            "NATIVE_VOLUME_24H",
                            "TX_COUNT_24H",
                            "HOLDERS",
                            "INITIALIZE_AT",
                            "Links"
                        ],
                        "type": "string",
                        "example": "\"INITIALIZE_AT\"",
                        "description": "排序字段，支持以下值：MARKET_CAP, PRICE_CHANGE_5M, PRICE_CHANGE_1H, PRICE_CHANGE_24H, NATIVE_VOLUME_1H, NATIVE_VOLUME_24H, TX_COUNT_24H, HOLDERS, INITIALIZE_AT, Links",
                        "name": "sorted_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "DESC",
                            "ASC"
                        ],
                        "type": "string",
                        "example": "\"DESC\"",
                        "description": "排序方向，支持以下值：DESC, ASC",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"\"",
                        "description": "分页游标，用于分页查询",
                        "name": "page_cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 50,
                        "description": "每页返回的数据条数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"\"",
                        "description": "搜索关键字，用于筛选数据",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "1D",
                            "1H",
                            "1M"
                        ],
                        "type": "string",
                        "example": "\"1D\"",
                        "description": "新交易对的时间分辨率，例如 1D（1 天）",
                        "name": "new_pairs_resolution",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回市场行情数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TickersResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/swap_histories/{tickers_id}": {
            "get": {
                "description": "根据 Ticker ID 获取交易历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取指定 Ticker 的交易历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"SUPER\"",
                        "description": "Ticker ID",
                        "name": "tickers_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回交易历史记录",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SwapHistoriesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{tickers_id}/distribution": {
            "get": {
                "description": "根据 Ticker ID 获取代币持有者的分布信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取指定 Ticker 的代币分布信息",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"SUPER\"",
                        "description": "Ticker ID",
                        "name": "tickers_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币分布信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenDistributionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tickers/{token_symbol}": {
            "get": {
                "description": "根据 token_symbol 获取 Ticker 的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "市场行情"
                ],
                "summary": "获取 Ticker 详情",
                "parameters": [
                    {
                        "enum": [
                            "SUPER",
                            "BTC",
                            "ETH",
                            "USDT",
                            "BNB"
                        ],
                        "type": "string",
                        "example": "\"SUPER\"",
                        "description": "代币符号",
                        "name": "token_symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 Ticker 详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.GetTickerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/token_holdings/histories/{account}": {
            "get": {
                "description": "根据用户账户获取代币持仓历史数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "代币持仓"
                ],
                "summary": "获取代币持仓历史数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0",
                        "description": "分页页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "20",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币持仓历史数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenHoldingHistoriesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/token_holdings/{account}": {
            "get": {
                "description": "根据用户账户和目标账户获取代币持仓数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "代币持仓"
                ],
                "summary": "获取代币持仓数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标账户",
                        "name": "account",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "false",
                        "description": "是否包含零余额",
                        "name": "allow_zero_balance",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回代币持仓数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.TokenHoldingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tokens/{klineType}/{chainType}/{tokenAddress}": {
            "get": {
                "description": "Get historical kline (candlestick) data for a specific token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "on-chain-data"
                ],
                "summary": "Get token kline data",
                "parameters": [
                    {
                        "enum": [
                            "kline",
                            "mcapkline"
                        ],
                        "type": "string",
                        "description": "Kline type",
                        "name": "klineType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "sol",
                            "eth",
                            "btc"
                        ],
                        "type": "string",
                        "description": "Chain type",
                        "name": "chainType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token address",
                        "name": "tokenAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resolution (1S=1sec, 1=1min, 5=5min, 15=15min, 60=1hour, 240=4hour, 720=12hour, 1D=1day)",
                        "name": "resolution",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.KlineData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "通过钱包地址和签名进行登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户钱包登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users/my_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据 JWT Token 获取当前用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.MyInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/ws/kline/{tokenAddress}": {
            "get": {
                "description": "通过 WebSocket 实时推送 K 线数据。连接成功后，服务器将每秒推送最新的K线数据。\n连接格式: ws://host/ws/kline/{tokenAddress}?resolution={resolution}\n示例: ws://localhost:8080/ws/kline/0x1234...?resolution=1S",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "K线数据 WebSocket 接口",
                "parameters": [
                    {
                        "type": "string",
                        "example": "0x1234567890abcdef1234567890abcdef12345678",
                        "description": "代币地址",
                        "name": "tokenAddress",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "1S",
                            "1",
                            "5",
                            "15",
                            "60",
                            "240",
                            "720",
                            "1D"
                        ],
                        "type": "string",
                        "example": "1S",
                        "description": "K线周期",
                        "name": "resolution",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket连接成功后的推送数据格式",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.KlineData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "close": {
                                            "type": "string"
                                        },
                                        "high": {
                                            "type": "string"
                                        },
                                        "low": {
                                            "type": "string"
                                        },
                                        "open": {
                                            "type": "string"
                                        },
                                        "timestamp": {
                                            "type": "integer"
                                        },
                                        "volume": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "description": "用户登录时提交的请求参数",
            "type": "object",
            "properties": {
                "address": {
                    "description": "用户钱包地址",
                    "type": "string",
                    "example": "F59CSoJEmjDFQWZMjSjjvu6q7xV31p9rPzRynwrE71yk"
                },
                "comment_id": {
                    "description": "评论ID（可选）",
                    "type": "string",
                    "example": ""
                },
                "invite_code": {
                    "description": "邀请码（可选）",
                    "type": "string",
                    "example": "INVITE123"
                },
                "message": {
                    "description": "登录消息",
                    "type": "string",
                    "example": "Sign in to the super.exchange\r\n\r\nTimestamp: 1740885327"
                },
                "post_id": {
                    "description": "帖子ID（可选）",
                    "type": "string",
                    "example": ""
                },
                "signature": {
                    "description": "签名信息",
                    "type": "string",
                    "example": "Pli28P7PHx6Mzh+RwRTcqtCSuNs2qlncAqC4tK9PFN/CLnvZ2Gm8koqvkLPEZNoiVJOX71hCBaQV9NUKVX8KDg=="
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string",
                    "example": "1740885327"
                }
            }
        },
        "response.GetTickerResponse": {
            "description": "Ticker 的具体数据",
            "type": "object",
            "properties": {
                "market": {
                    "description": "市场信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Market"
                        }
                    ]
                },
                "market_metadata": {
                    "description": "市场元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketMetadata"
                        }
                    ]
                },
                "market_ticker": {
                    "description": "市场行情",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketTicker"
                        }
                    ]
                }
            }
        },
        "response.KlineData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "response.LoginResponse": {
            "description": "登录成功后返回的具体数据",
            "type": "object",
            "properties": {
                "invite_code": {
                    "description": "邀请码",
                    "type": "string",
                    "example": ""
                },
                "token": {
                    "description": "登录令牌",
                    "type": "string",
                    "example": "_vetZFMHLOlPWer8_uTrqe5_7gGGNPi-fvD--pomTdSd2kn3po2uBujC4o7raUiNHPpKJaS_BR3jmgOEdaAEFA=="
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserInfo"
                        }
                    ]
                }
            }
        },
        "response.Market": {
            "description": "市场的基本信息",
            "type": "object",
            "properties": {
                "create_timestamp": {
                    "description": "创建时间戳",
                    "type": "integer",
                    "example": 1740033455
                },
                "creator": {
                    "description": "创建者地址",
                    "type": "string",
                    "example": "3P3PMv28AM7SvNkGmAdHCusPwahSB9QG9z5o4gTvmNBX"
                },
                "holders": {
                    "description": "持有者数量",
                    "type": "integer",
                    "example": 4204
                },
                "market": {
                    "description": "市场地址",
                    "type": "string",
                    "example": "B3o198GX45DZ9HeJZ56wuruyWWCfGVBSn5qC71q5AHZz"
                },
                "market_id": {
                    "description": "市场ID",
                    "type": "integer",
                    "example": 1
                },
                "native_vault": {
                    "description": "原生代币金库地址",
                    "type": "string",
                    "example": "98J2RACW3wk8u36k1cPmDenzHdPjhcd5qXsm5g471kdh"
                },
                "price": {
                    "description": "当前价格",
                    "type": "string",
                    "example": "0.000050417320729"
                },
                "token_mint": {
                    "description": "代币铸造地址",
                    "type": "string",
                    "example": "suprkbfvwpFZXzWaoKjTzGkW1nkvvwK9n2E6g1zyLFo"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string",
                    "example": "§uper Exchange"
                },
                "token_symbol": {
                    "description": "代币符号",
                    "type": "string",
                    "example": "SUPER"
                },
                "token_vault": {
                    "description": "代币金库地址",
                    "type": "string",
                    "example": "9SQy9T4pzadupDcWdYYgFmUgXLVydfQwgKZEbzeACNAQ"
                },
                "uri": {
                    "description": "URI",
                    "type": "string",
                    "example": "https://static.super.exchange/m/official/super.json"
                }
            }
        },
        "response.MarketMetadata": {
            "description": "市场的元数据信息",
            "type": "object",
            "properties": {
                "banner": {
                    "description": "横幅图片",
                    "type": "string",
                    "example": ""
                },
                "description": {
                    "description": "描述",
                    "type": "string",
                    "example": ""
                },
                "image_url": {
                    "description": "图片URL",
                    "type": "string",
                    "example": "https://static.super.exchange/i/official/super.png"
                },
                "rules": {
                    "description": "规则",
                    "type": "string",
                    "example": ""
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "example": 0
                },
                "telegram": {
                    "description": "Telegram链接",
                    "type": "string",
                    "example": "https://t.me/SuperExchangeCommunity"
                },
                "twitter": {
                    "description": "Twitter链接",
                    "type": "string",
                    "example": "https://x.com/_superexchange"
                },
                "website": {
                    "description": "网站链接",
                    "type": "string",
                    "example": "https://super.exchange"
                }
            }
        },
        "response.MarketTicker": {
            "description": "市场的行情数据",
            "type": "object",
            "properties": {
                "buy_native_volume_1h": {
                    "description": "1小时买入原生代币交易量",
                    "type": "string",
                    "example": "19.071274881"
                },
                "buy_native_volume_24h": {
                    "description": "24小时买入原生代币交易量",
                    "type": "string",
                    "example": "703.884254256"
                },
                "buy_native_volume_5m": {
                    "description": "5分钟买入原生代币交易量",
                    "type": "string",
                    "example": "3.138140370"
                },
                "buy_token_volume_1h": {
                    "description": "1小时买入代币交易量",
                    "type": "string",
                    "example": "379231.972430"
                },
                "buy_token_volume_24h": {
                    "description": "24小时买入代币交易量",
                    "type": "string",
                    "example": "15435782.918031"
                },
                "buy_token_volume_5m": {
                    "description": "5分钟买入代币交易量",
                    "type": "string",
                    "example": "62269.324250"
                },
                "buy_tx_count_1h": {
                    "description": "1小时买入交易次数",
                    "type": "integer",
                    "example": 271
                },
                "buy_tx_count_24h": {
                    "description": "24小时买入交易次数",
                    "type": "integer",
                    "example": 7566
                },
                "buy_tx_count_5m": {
                    "description": "5分钟买入交易次数",
                    "type": "integer",
                    "example": 25
                },
                "high_1h": {
                    "description": "1小时最高价",
                    "type": "string",
                    "example": "0.000050417320729"
                },
                "high_24h": {
                    "description": "24小时最高价",
                    "type": "string",
                    "example": "0.000050417320729"
                },
                "high_5m": {
                    "description": "5分钟最高价",
                    "type": "string",
                    "example": "0.000050417320729"
                },
                "last_swap_at": {
                    "description": "最后交易时间戳",
                    "type": "integer",
                    "example": 1740887399
                },
                "low_1h": {
                    "description": "1小时最低价",
                    "type": "string",
                    "example": "0.000050161350930"
                },
                "low_24h": {
                    "description": "24小时最低价",
                    "type": "string",
                    "example": "0.000041158184158"
                },
                "low_5m": {
                    "description": "5分钟最低价",
                    "type": "string",
                    "example": "0.000050375183502"
                },
                "market_cap": {
                    "description": "市值",
                    "type": "string",
                    "example": "50417.320729000000000"
                },
                "native_volume_1h": {
                    "description": "1小时原生代币交易量",
                    "type": "string",
                    "example": "19.071274881"
                },
                "native_volume_24h": {
                    "description": "24小时原生代币交易量",
                    "type": "string",
                    "example": "704.558749824"
                },
                "native_volume_5m": {
                    "description": "5分钟原生代币交易量",
                    "type": "string",
                    "example": "3.138140370"
                },
                "price_change_1h": {
                    "description": "1小时价格变化",
                    "type": "string",
                    "example": "0.005103"
                },
                "price_change_24h": {
                    "description": "24小时价格变化",
                    "type": "string",
                    "example": "0.224965"
                },
                "price_change_5m": {
                    "description": "5分钟价格变化",
                    "type": "string",
                    "example": "0.000836"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer",
                    "example": 1
                },
                "token_volume_1h": {
                    "description": "1小时代币交易量",
                    "type": "string",
                    "example": "379231.972430"
                },
                "token_volume_24h": {
                    "description": "24小时代币交易量",
                    "type": "string",
                    "example": "15450301.872331"
                },
                "token_volume_5m": {
                    "description": "5分钟代币交易量",
                    "type": "string",
                    "example": "62269.324250"
                },
                "tx_count_1h": {
                    "description": "1小时交易次数",
                    "type": "integer",
                    "example": 271
                },
                "tx_count_24h": {
                    "description": "24小时交易次数",
                    "type": "integer",
                    "example": 7590
                },
                "tx_count_5m": {
                    "description": "5分钟交易次数",
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "response.Moderator": {
            "description": "持有者的管理员信息",
            "type": "object",
            "properties": {
                "banned": {
                    "description": "是否被封禁",
                    "type": "boolean",
                    "example": false
                },
                "banned_mod_id": {
                    "description": "被封禁的 Moderator ID",
                    "type": "integer",
                    "example": 0
                },
                "status": {
                    "description": "当前状态",
                    "type": "string",
                    "example": "NORMAL"
                }
            }
        },
        "response.MyInfoResponse": {
            "description": "包含用户基本信息、社交统计、邀请码等详细信息。",
            "type": "object",
            "properties": {
                "fan_count": {
                    "description": "关注数量",
                    "type": "integer"
                },
                "follow_status": {
                    "description": "关注状态",
                    "type": "string"
                },
                "follower_count": {
                    "description": "粉丝数量",
                    "type": "integer"
                },
                "has_bound": {
                    "description": "是否已绑定",
                    "type": "boolean"
                },
                "invite_code": {
                    "description": "邀请码",
                    "type": "string"
                },
                "mention_count": {
                    "description": "提及数量",
                    "type": "integer"
                },
                "user": {
                    "description": "用户基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserInfo"
                        }
                    ]
                },
                "vote_count": {
                    "description": "投票数量",
                    "type": "integer"
                }
            }
        },
        "response.PayerProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "用户头像",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户 ID",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SwapHistoriesResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "description": "是否还有更多数据",
                    "type": "boolean"
                },
                "transaction_histories": {
                    "description": "交易历史记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TransactionHistory"
                    }
                }
            }
        },
        "response.TickerItem": {
            "description": "单个市场的详细信息",
            "type": "object",
            "properties": {
                "market": {
                    "description": "市场信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Market"
                        }
                    ]
                },
                "market_metadata": {
                    "description": "市场元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketMetadata"
                        }
                    ]
                },
                "market_ticker": {
                    "description": "市场行情",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.MarketTicker"
                        }
                    ]
                }
            }
        },
        "response.TickersResponse": {
            "description": "市场行情的具体数据",
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "分页游标",
                    "type": "string",
                    "example": "NTA0MTcuMzIwNzI5MDAwMDAwMDAwOjE="
                },
                "has_more": {
                    "description": "是否有更多数据",
                    "type": "boolean",
                    "example": true
                },
                "list": {
                    "description": "市场列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TickerItem"
                    }
                }
            }
        },
        "response.TokenBalance": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "decimals": {
                    "type": "integer"
                },
                "owner": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "response.TokenDistributionResponse": {
            "description": "代币持有者数据",
            "type": "object",
            "properties": {
                "token_holders": {
                    "description": "代币持有者列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHolder"
                    }
                }
            }
        },
        "response.TokenHolder": {
            "description": "代币持有者详情",
            "type": "object",
            "properties": {
                "account": {
                    "description": "持有者钱包地址",
                    "type": "string",
                    "example": "669VYcBRq51iQzFiPTQcsW2CsvLfHM9AwVmaoM1mAAR7"
                },
                "is_associated_bonding_curve": {
                    "description": "是否与 Bonding Curve 关联",
                    "type": "boolean",
                    "example": false
                },
                "is_black_hole": {
                    "description": "是否为黑洞地址",
                    "type": "boolean",
                    "example": false
                },
                "is_community_vault": {
                    "description": "是否为社区金库",
                    "type": "boolean",
                    "example": false
                },
                "moderator": {
                    "description": "持有者的管理员信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Moderator"
                        }
                    ]
                },
                "percentage": {
                    "description": "持有代币的百分比",
                    "type": "string",
                    "example": "100.000000"
                },
                "user_profile": {
                    "description": "用户资料（可能为空）"
                }
            }
        },
        "response.TokenHolding": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "持仓数量",
                    "type": "string"
                },
                "filled_price": {
                    "description": "成交价格",
                    "type": "string"
                },
                "holders_count": {
                    "description": "持有者数量",
                    "type": "integer"
                },
                "id": {
                    "description": "代币 ID",
                    "type": "integer"
                },
                "image_uri": {
                    "description": "代币图片 URI",
                    "type": "string"
                },
                "market_address": {
                    "description": "市场地址",
                    "type": "string"
                },
                "market_id": {
                    "description": "市场 ID",
                    "type": "integer"
                },
                "price": {
                    "description": "当前价格",
                    "type": "string"
                },
                "realized_pnl": {
                    "description": "已实现盈亏",
                    "type": "string"
                },
                "symbol": {
                    "description": "代币符号",
                    "type": "string"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string"
                },
                "total_buy": {
                    "description": "总买入数量",
                    "type": "string"
                },
                "total_buy_native": {
                    "description": "总买入原生代币数量",
                    "type": "string"
                },
                "total_sell": {
                    "description": "总卖出数量",
                    "type": "string"
                },
                "total_sell_native": {
                    "description": "总卖出原生代币数量",
                    "type": "string"
                },
                "total_value": {
                    "description": "持仓总价值",
                    "type": "string"
                }
            }
        },
        "response.TokenHoldingHistoriesResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "description": "是否有更多数据",
                    "type": "boolean"
                },
                "token_holdings_histories": {
                    "description": "代币持仓历史列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHoldingHistory"
                    }
                }
            }
        },
        "response.TokenHoldingHistory": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "持仓数量",
                    "type": "string"
                },
                "filled_price": {
                    "description": "成交价格",
                    "type": "string"
                },
                "holders_count": {
                    "description": "持有者数量",
                    "type": "integer"
                },
                "id": {
                    "description": "记录 ID",
                    "type": "integer"
                },
                "image_uri": {
                    "description": "代币图片 URI",
                    "type": "string"
                },
                "market_address": {
                    "description": "市场地址",
                    "type": "string"
                },
                "market_id": {
                    "description": "市场 ID",
                    "type": "integer"
                },
                "price": {
                    "description": "当前价格",
                    "type": "string"
                },
                "realized_pnl": {
                    "description": "已实现盈亏",
                    "type": "string"
                },
                "symbol": {
                    "description": "代币符号",
                    "type": "string"
                },
                "token_name": {
                    "description": "代币名称",
                    "type": "string"
                },
                "total_buy": {
                    "description": "总买入数量",
                    "type": "string"
                },
                "total_buy_native": {
                    "description": "总买入原生代币数量",
                    "type": "string"
                },
                "total_sell": {
                    "description": "总卖出数量",
                    "type": "string"
                },
                "total_sell_native": {
                    "description": "总卖出原生代币数量",
                    "type": "string"
                },
                "total_value": {
                    "description": "持仓总价值",
                    "type": "string"
                }
            }
        },
        "response.TokenHoldingsResponse": {
            "type": "object",
            "properties": {
                "token_holdings": {
                    "description": "代币持仓列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TokenHolding"
                    }
                }
            }
        },
        "response.TransactionHistory": {
            "type": "object",
            "properties": {
                "block_time": {
                    "description": "区块时间",
                    "type": "string"
                },
                "fee": {
                    "description": "手续费",
                    "type": "string"
                },
                "id": {
                    "description": "交易 ID",
                    "type": "integer"
                },
                "index": {
                    "description": "交易索引",
                    "type": "integer"
                },
                "is_buy": {
                    "description": "是否为买入",
                    "type": "boolean"
                },
                "market_id": {
                    "description": "市场 ID",
                    "type": "integer"
                },
                "native_amount": {
                    "description": "原生代币数量",
                    "type": "string"
                },
                "payer": {
                    "description": "支付方地址",
                    "type": "string"
                },
                "payer_profile": {
                    "description": "支付方信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.PayerProfile"
                        }
                    ]
                },
                "recipient": {
                    "description": "接收方地址",
                    "type": "string"
                },
                "signature": {
                    "description": "交易签名",
                    "type": "string"
                },
                "slot": {
                    "description": "区块槽位",
                    "type": "integer"
                },
                "token_amount": {
                    "description": "代币数量",
                    "type": "string"
                },
                "total_native_amount": {
                    "description": "总原生代币数量",
                    "type": "string"
                }
            }
        },
        "response.UserInfo": {
            "description": "包含用户 ID、地址、昵称、头像和描述等信息。",
            "type": "object",
            "properties": {
                "address": {
                    "description": "用户地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "用户头像",
                    "type": "string"
                },
                "description": {
                    "description": "用户描述",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户 ID",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "8.218.102.112:4998",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "My API",
	Description:      "This is a sample API for demonstration purposes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
